---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: monitoring
  labels:
    app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
      - type: log
        enabled: true
      paths:
        - /var/log/*.log
    output.logstash:
      hosts: ['logstash-service:5044']

<<<<<<< HEAD
#---
 #   apiVersion: v1
  #  kind: ConfigMap
   # metadata:
    #  name: filebeat-prospectors
     # namespace: monitoring
      #labels:
       # app: filebeat
   # data:
    #   kubernetes.yml: |-
     #    - type: docker
      #     containers.ids:
       #    - "*"
        #   processors:
         #    - add_kubernetes_metadata:
          #       in_cluster: true

=======
---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: filebeat-prospectors
      namespace: monitoring
      labels:
        app: filebeat
    data:
       kubernetes.yml: |-
         - type: docker
           containers.ids:
           - "*"
           processors:
             - add_kubernetes_metadata:
                 in_cluster: true
>>>>>>> parent of 2bc65ae... Modification done in all elk yaml files
