apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

# Create namespace
  - ./elk/namespace.yaml
  
# Deploy elasticsearch
  - ./elk/elasticsearch/elastic_serviceAccount.yaml
  - ./elk/elasticsearch/elastic_clusterRole.yaml
  - ./elk/elasticsearch/elastic_clusterRoleBinding.yaml
  - ./elk/elasticsearch/elasticsearch_deploy.yaml
  - ./elk/elasticsearch/elasticsearch_service.yaml

# Deploy Logstash
  - ./elk/logstash/configMap.yaml
  - ./elk/logstash/logstash_deploy.yaml
  - ./elk/logstash/logstash_service.yaml

# Deploy Kibana
  - ./elk/kibana/kibana_deploy.yaml
  - ./elk/kibana/kibana_service.yaml

# Deploy Filebeat
  - ./elk/filebeat/configMap.yaml
  - ./elk/filebeat/filebeat_clusterRole.yaml
  - ./elk/filebeat/filebeat_clusterRoleBinding.yaml
  - ./elk/filebeat/filebeat_deploy.yaml
  - ./elk/filebeat/filebeat_serviceAccount.yaml

