apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: monitoring
  labels:
    app: kibana-logging
spec:
  type: NodePort
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
    nodePort: 32000
  selector:
    app: kibana-logging
