---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-logging
  namespace: monitoring
  labels:
    app: kibana-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-logging
  template:
    metadata:
      labels:
        app: kibana-logging
    spec:
      containers:
      - name: kibana-logging
        image: docker.elastic.co/kibana/kibana-oss:6.8.4
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch-logging:9200
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        resources:
          requests:
            cpu: "100m"
            memory: "250Mi"
          limits:
            cpu: "600m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /
            port: 5601
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1  
        readinessProbe:
          httpGet:
            path: /
            port: 5601
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 2
          failureThreshold: 3
          timeoutSeconds: 2
