---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
  namespace: monitoring
  labels:
    app: logstash
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:6.3.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5044
        resources:
          requests:
            cpu: "600m"
            memory: "500Mi"
          limits:
            cpu: "600m"
            memory: "1Gi"
        livenessProbe:
          tcpSocket:
            port: 9600
          initialDelaySeconds: 120
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 10  
        readinessProbe:
          tcpSocket:
            port: 9600
          initialDelaySeconds: 120
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 10
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/logstash/config
          - name: logstash-pipeline-volume
            mountPath: /usr/share/logstash/pipeline
      volumes:
        - name: config-volume
          configMap:
            name: logstash-configmap
            items:
              - key: logstash.yml
                path: logstash.yml
        - name: logstash-pipeline-volume
          configMap:
            name: logstash-configmap
            items:
              - key: logstash.conf
                path: logstash.conf
      restartPolicy: Always
